//// Code generated by protoc-gen-go. DO NOT EDIT.
//// versions:
//// 	protoc-gen-go v1.26.0
//// 	protoc        v3.13.0
//// source: foo.proto
//
package examples

//
//import (
//	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
//	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
//	reflect "reflect"
//	sync "sync"
//)
//
//const (
//	// Verify that this generated code is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
//	// Verify that runtime/protoimpl is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
//)
//
//type HelloN int32
//
//const (
//	Hello_foonum HelloN = 0
//	Hello_barnum HelloN = 1
//)
//
//// Enum value maps for HelloN.
//var (
//	HelloN_name = map[int32]string{
//		0: "foonum",
//		1: "barnum",
//	}
//	HelloN_value = map[string]int32{
//		"foonum": 0,
//		"barnum": 1,
//	}
//)
//
//func (x HelloN) Enum() *HelloN {
//	p := new(HelloN)
//	*p = x
//	return p
//}
//
//func (x HelloN) String() string {
//	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
//}
//
//func (HelloN) Descriptor() protoreflect.EnumDescriptor {
//	return file_foo_proto_enumTypes[0].Descriptor()
//}
//
//func (HelloN) Type() protoreflect.EnumType {
//	return &file_foo_proto_enumTypes[0]
//}
//
//func (x HelloN) Number() protoreflect.EnumNumber {
//	return protoreflect.EnumNumber(x)
//}
//
//// Deprecated: Use HelloN.Descriptor instead.
//func (HelloN) EnumDescriptor() ([]byte, []int) {
//	return file_foo_proto_rawDescGZIP(), []int{1, 0}
//}
//
//type Bar struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Baz string `protobuf:"bytes,1,opt,name=baz,proto3" json:"baz,omitempty"`
//}
//
//func (x *Bar) Reset() {
//	*x = Bar{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_foo_proto_msgTypes[0]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *Bar) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*Bar) ProtoMessage() {}
//
//func (x *Bar) ProtoReflect() protoreflect.Message {
//	mi := &file_foo_proto_msgTypes[0]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
//func (*Bar) Descriptor() ([]byte, []int) {
//	return file_foo_proto_rawDescGZIP(), []int{0}
//}
//
//func (x *Bar) GetBaz() string {
//	if x != nil {
//		return x.Baz
//	}
//	return ""
//}
//
//type Hello struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	World    string `protobuf:"bytes,2,opt,name=world,proto3" json:"world,omitempty"`
//	Universe bool   `protobuf:"varint,3,opt,name=universe,proto3" json:"universe,omitempty"`
//}
//
//func (x *Hello) Reset() {
//	*x = Hello{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_foo_proto_msgTypes[1]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *Hello) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*Hello) ProtoMessage() {}
//
//func (x *Hello) ProtoReflect() protoreflect.Message {
//	mi := &file_foo_proto_msgTypes[1]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
//func (*Hello) Descriptor() ([]byte, []int) {
//	return file_foo_proto_rawDescGZIP(), []int{1}
//}
//
//func (x *Hello) GetWorld() string {
//	if x != nil {
//		return x.World
//	}
//	return ""
//}
//
//func (x *Hello) GetUniverse() bool {
//	if x != nil {
//		return x.Universe
//	}
//	return false
//}
//
//var File_foo_proto protoreflect.FileDescriptor
//
//var file_foo_proto_rawDesc = []byte{
//	0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x73,
//	0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x03, 0x42, 0x61, 0x72,
//	0x12, 0x10, 0x0a, 0x03, 0x62, 0x61, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62,
//	0x61, 0x7a, 0x22, 0x56, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x77,
//	0x6f, 0x72, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6c,
//	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x18, 0x03, 0x20,
//	0x01, 0x28, 0x08, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x22, 0x1b, 0x0a,
//	0x01, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x6e, 0x75, 0x6d, 0x10, 0x00, 0x12, 0x0a,
//	0x0a, 0x06, 0x62, 0x61, 0x72, 0x6e, 0x75, 0x6d, 0x10, 0x01, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
//	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f,
//	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x61,
//	0x6d, 0x70, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
//}
//
//var (
//	file_foo_proto_rawDescOnce sync.Once
//	file_foo_proto_rawDescData = file_foo_proto_rawDesc
//)
//
//func file_foo_proto_rawDescGZIP() []byte {
//	file_foo_proto_rawDescOnce.Do(func() {
//		file_foo_proto_rawDescData = protoimpl.X.CompressGZIP(file_foo_proto_rawDescData)
//	})
//	return file_foo_proto_rawDescData
//}
//
//var file_foo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
//var file_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
//var file_foo_proto_goTypes = []interface{}{
//	(HelloN)(0),   // 0: cosmos.proto.Hello.n
//	(*Bar)(nil),   // 1: cosmos.proto.Bar
//	(*Hello)(nil), // 2: cosmos.proto.Hello
//}
//var file_foo_proto_depIdxs = []int32{
//	0, // [0:0] is the sub-list for method output_type
//	0, // [0:0] is the sub-list for method input_type
//	0, // [0:0] is the sub-list for extension type_name
//	0, // [0:0] is the sub-list for extension extendee
//	0, // [0:0] is the sub-list for field type_name
//}
//
//func init() { file_foo_proto_init() }
//func file_foo_proto_init() {
//	if File_foo_proto != nil {
//		return
//	}
//	if !protoimpl.UnsafeEnabled {
//		file_foo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*Bar); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_foo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*Hello); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//	}
//	type x struct{}
//	out := protoimpl.TypeBuilder{
//		File: protoimpl.DescBuilder{
//			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
//			RawDescriptor: file_foo_proto_rawDesc,
//			NumEnums:      1,
//			NumMessages:   2,
//			NumExtensions: 0,
//			NumServices:   0,
//		},
//		GoTypes:           file_foo_proto_goTypes,
//		DependencyIndexes: file_foo_proto_depIdxs,
//		EnumInfos:         file_foo_proto_enumTypes,
//		MessageInfos:      file_foo_proto_msgTypes,
//	}.Build()
//	File_foo_proto = out.File
//	file_foo_proto_rawDesc = nil
//	file_foo_proto_goTypes = nil
//	file_foo_proto_depIdxs = nil
//}
